# Generated by Django 5.2.7 on 2025-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('author', 'Author'), ('common_user', 'Common User')], default='common_user', max_length=20),
        ),
    ]
