# Generated by Django 5.2.7 on 2025-10-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
    ]
